### ISSUE TITLE
Iteration 4 Progress Report

### ISSUE THREAD

**Issue by y123ob** [jtjun/DutchBroomstick#38]
# Iteration 4: 2019. 5. 24. ~ 2019. 6. 4.

# 계획
- Layer, Credit, Payment

- 13~16,26 RoomPage 미구현 부분 추가구현
- 17 AddPopup Toastr 이용하여 구현
- 27 RoomSettingPage
- 18,19 CreditListPage
- 20,28,22 CreditDetailPage

# 역할 분배
== 태준 ==
- Later, Credit, Payment(Backend)

== 정민 ==
- 백엔드 연동
- 테스트 케이스 작업
- 13~16,26 RoomPage
- AWS

== 유석 ==
- 17 AddPopup
- 27 RoomSettingPage
- 18,19 CreditListPage
- 20,28,22 CreditDetailPage
- 문서관리 (Docs)

**Comment by GBS-Skile** [comment]
6월 4일까지 완료된 작업 목록:

## 태준
- [x] (백엔드) Layer, Credit, Payment 모델 추가 #39 #41
- [x] 문서 관리 #39 [커밋](https://github.com/jtjun/DutchBroomstick/commit/ec48dd7efc3957afc371cfa5a49b1902f029d5aa) [커밋](https://github.com/jtjun/DutchBroomstick/commit/0aefd579f4fb0e4e8cc5ceaa3509d892d842eee0)
- [x] [Design Demo Update](https://github.com/jtjun/DutchBroomstick/commit/91c2279d52ea7955961fd0e2e02f9c64faf0e910)

## 정민
- [x] 백엔드-프론트엔드 연동 #40 #43 
  - [ ] User Story 13, 14, 15, 16 RoomPage
  - Iter 3. 에서 미처 못 끝냈던 Room CRUD 로직 마무리
  - 토큰 활용 로그인 패턴 구현, RoomCreatePage에 sagas 모듈 붙임
  - #39 에서 발견된 버그 수정
- [ ] 테스트 케이스 작업
- [x] AWS 배포 : 현재 #43 까지 Merge된 버전이 [테스트 서버](http://skile.me:3000)에 올라와 있음

## 유석
- [ ] User Story 17 AddPopup
- [x] User Story 27 RoomSettingPage #46
- [x] User Story 18, 19 CreditListPage #46
- [ ] User Story 20, 28, 22 CreditDetailPage

**Comment by GBS-Skile** [comment]
테스트 코드를 Iteration 4 기간동안 수정하지 않은 상태라서, 테스트 결과는 [Iteration 3 Progress Report](https://github.com/jtjun/DutchBroomstick/issues/27)와 동일합니다. Iteration 5에서 Travis CI 오류를 최우선으로 수정할 계획입니다.
